const TerminologyArray = [
  "White Blood Cell Count",
  "Red Blood Cell Count",
  "Hemoglobin",
  "Hematocrit",
  "Mean Corpuscular Volume (MCV)",
  "Mean Corpuscular Hemoglobin (MCH)",
  "Mean Corpuscular Hemoglobin Concentration (MCHC)",
  "Red Cell Distribution Width (RDW)",
  "Platelet Count",
  "Mean Platelet Volume (MPV)",
  "Neutrophils",
  "Lymphocytes",
  "Monocytes",
  "Eosinophils",
  "Basophils",
  "Glucose",
  "Calcium",
  "Sodium",
  "Potassium",
  "Chloride",
  "Carbon Dioxide (Bicarbonate)",
  "Blood Urea Nitrogen (BUN)",
  "Creatinine",
  "Albumin",
  "Total Protein",
  "Alanine Aminotransferase (ALT)",
  "Aspartate Aminotransferase (AST)",
  "Alkaline Phosphatase (ALP)",
  "Total Bilirubin",
  "Direct Bilirubin",
  "Indirect Bilirubin",
  "Gamma-Glutamyl Transferase (GGT)",
  "Globulin",
  "Albumin/Globulin Ratio",
  "Lactate Dehydrogenase (LDH)",
  "Total Cholesterol",
  "Low-Density Lipoprotein (LDL) Cholesterol",
  "High-Density Lipoprotein (HDL) Cholesterol",
  "Triglycerides",
  "Very Low-Density Lipoprotein (VLDL) Cholesterol",
  "Non-HDL Cholesterol",
  "BUN/Creatinine Ratio",
  "Glomerular Filtration Rate (GFR)",
  "Uric Acid",
  "Phosphorus(standardized from Phosphate)",
  "Thyroid Stimulating Hormone (TSH)",
  "Free Thyroxine (Free T4)",
  "Free Triiodothyronine (Free T3)",
  "Total Thyroxine (Total T4)",
  "Total Triiodothyronine (Total T3)",
  "Urinal Color",
  "Urinal Clarity",
  "Urinal pH",
  "Urinal Specific Gravity",
  "Urinal Protein",
  "Urinal Ketones",
  "Urinal Bilirubin",
  "Urinal Urobilinogen",
  "Urinal Nitrite",
  "Urinal Leukocyte Esterase",
  "Urinal Casts",
  "Urinal Crystals",
  "Urinal Bacteria",
  "Troponin",
  "Creatine Kinase-MB (CK-MB)",
  "Myoglobin",
  "B-type Natriuretic Peptide (BNP)",
  "C-Reactive Protein (CRP)",
  "Prothrombin Time (PT)",
  "International Normalized Ratio (INR)",
  "Activated Partial Thromboplastin Time (aPTT)",
  "Fibrinogen",
  "D-Dimer",
  "Testosterone",
  "Estradiol",
  "Progesterone",
  "Luteinizing Hormone (LH)",
  "Follicle-Stimulating Hormone (FSH)",
  "Cortisol",
  "Prolactin",
  "Vitamin A",
  "Vitamin B1 (Thiamine)",
  "Vitamin B2 (Riboflavin)",
  "Vitamin B3 (Niacin)",
  "Vitamin B5 (Pantothenic Acid)",
  "Vitamin B6 (Pyridoxine)",
  "Vitamin B7 (Biotin)",
  "Vitamin B9 (Folate)",
  "Vitamin B12 (Cobalamin)",
  "Vitamin C",
  "Vitamin D (25-Hydroxy)",
  "Vitamin E",
  "Vitamin K",
  "Serum Iron",
  "Total Iron-Binding Capacity (TIBC)",
  "Ferritin",
  "Transferrin Saturation",
  "Arterial Blood Gas pH",
  "Partial Pressure of Oxygen (PaO2)",
  "Partial Pressure of Carbon Dioxide (PaCO2)",
  "Bicarbonate (HCO3)",
  "Oxygen Saturation (O2Sat)",
  "Erythrocyte Sedimentation Rate (ESR)",
  "Prostate-Specific Antigen (PSA)",
  "Hepatitis A Antibody",
  "Hepatitis B Surface Antigen",
  "Hepatitis C Antibody",
  "HIV Antibody",
  "HIV Antigen",
  "Chlamydia",
  "Gonorrhea",
  "Syphilis",
  "Herpes Simplex Virus",
  "HbA1c",
  "Estimated average glucose(eAG)",
  "Glucose, Fasting (F)",
];

module.exports = TerminologyArray;
